const TestimonialApi = [
    {
      id: 1,
      image: "./image/slide1.png",
      design: "N/A",
      name: "N/A",
      offcer: "N/A",
      post: "N/A",
      date: "N/A",
      desc: "N/A",
    },
    {
      id: 2,
      image: "./image/slide2.png",
      design: "N/A",
      name: "N/A",
      offcer: "N/A",
      post: "N/A",
      date: "N/A",
      desc: "N/A",
    },
    {
      id: 3,
      image: "./image/slide3.png",
      design: "N/A",
      name: "N/A",
      offcer: "N/A",
      post: "N/A",
      date: "N/A",
      desc: "N/A",
    },
    {
      id: 4,
      image: "./image/slide4.png",
      design: "N/A",
      name: "N/A",
      offcer: "N/A",
      post: "N/A",
      date: "N/A",
      desc: "N/A",
    },
    {
      id: 5,
      image: "./image/slide5.png",
      design: "N/A",
      name: "N/A",
      offcer: "N/A",
      post: "N/A",
      date: "N/A",
      desc: "N/A",
    },
  ]
  
  export default TestimonialApi